/* ===================================================================
   森、道、市場 After party — データ定義
   出典：森、道、市場2026 公式サイト（https://morimichiichiba.jp/）
        ／公式アーティストページ／公式会場マップPDF「出店一覧」
   ・このアプリは感想投稿アプリ。下記データは「感想の対象」を選ぶための
     選択肢マスタとして用いる。出演日時・座標などの実情報は持たない。
   ・各レコードの src:'official' は出所が公式発表であることを示す。
=================================================================== */

/* データの出所（about画面で表示） */
const DATA_SOURCES = {
  artists: {
    name: '森、道、市場2026 公式アーティストページ',
    url: 'https://morimichiichiba.jp/artist/',
    retrieved: '2026-05-21'
  },
  shops: {
    name: '森、道、市場2026 公式会場マップPDF「出店一覧」',
    url: 'https://morimichiichiba.jp/map/',
    retrieved: '2026-05-21'
  },
  zones: {
    name: '森、道、市場2026 公式会場マップPDF',
    url: 'https://morimichiichiba.jp/map/',
    retrieved: '2026-05-21'
  }
};

const FESTIVAL = {
  name: '森、道、市場 2026',
  nameEn: 'MORI, MICHI, ICHIBA 2026',
  official: 'https://morimichiichiba.jp/',
  days: [
    { id: 'd1', label: '5/22', dow: 'FRI' },
    { id: 'd2', label: '5/23', dow: 'SAT' },
    { id: 'd3', label: '5/24', dow: 'SUN' }
  ]
};

/* 出演アーティスト（公式アーティストページ掲載順） */
const ARTIST_NAMES = [
  '∈Y∋','Aisho Nakajima','adieu','abentis','ecec','iga','石野卓球',
  'VMO a.k.a Violent Magic Orchestra','vq','West Ape','N²','FCO.','Elle',
  '大友良英','岡村靖幸','オカモトレイジ(OKAMOTO\'S)','掟ポルシェ','OddRe:',
  '思い出野郎Aチーム','角銅真実','片岡メリヤス × 井手健介','カネコアヤノ＋本村拓磨',
  'Kamui','Galileo Galilei','かわにしなつき','川辺素(BAND SET)',
  '川村亘平斎と岬の魔女たち','キタニタツヤ','君島大空(独奏)','奇妙礼太郎',
  '木村カエラ','きゃりーぱみゅぱみゅ','KIRINJI','草刈愛美','kurayamisaka','Kroi',
  'GUNSOKAI 郡囃会','ケケノコ族','コロコロチキチキペッパーズ ナダル','坂田律子',
  '坂本美雨 With 伊藤ゴロー','the cabs','さとうもか(Trio set)',
  '佐野元春 & THE COYOTE BAND','the bercedes menz','SAMO','さらさ(Duo Set)',
  'Shhhhh','SEEDA','Siero','6EYES','柴田聡子(BAND SET)','シャッポ','JUN INAGAWA',
  'Shoma fr,dambosound','Ginger Root(Solo Set)','神聖かまってちゃん','Jinmenusagi',
  '砂原良徳','SPECIAL OTHERS','Daoko','D.A.N.','珍盤亭娯楽師匠','discordsquad2k',
  'Texas 3000','TETORA','トップシークレットマン','とろサーモン久保田','長瀬有花',
  'nutsman','二階堂和美','NISENNENMONDAI','never young beach','野村友里(eatrip)',
  '蓮沼執太フィル','Hump Back','Peterparker69','ピーナッツくん','BBBBBBB','ヒカシュー',
  'BYORA','Billyrrom','5Windows Freak (DJ SET)','5 Star Cowboy','FELINE',
  'ブランデー戦記','BREIMEN','Frog 3','Bonbero','Mom','marucoporoporo',
  '向井秀徳アコースティック＆エレクトリック','MONO NO AWARE','YAGI YOYO TEAM',
  'やけのはら','柳瀬白瀬(from betcover!!)','Yog*','yonige','ヨネダ2000',
  'Lucky Kilimanjaro','ランジャタイ','lilbesh ramko','rui','レテ','ROBBIN(L.O.S.T)',
  'Worldwide Skippa','Watson'
];

/* エリア（公式会場マップPDF掲載のステージ・入口・主要エリア）
   形式: { id, name, type }  type: gate / stage / area */
const ZONES = [
  { id: 'west-gate', name: 'WEST ENTRANCE GATE', type: 'gate' },
  { id: 'east-gate', name: 'EAST ENTRANCE GATE', type: 'gate' },
  { id: 'art-stage', name: 'MORI MICHI ART THEATER', type: 'stage' },
  { id: 'park-stage', name: '遊園地STAGE', type: 'stage' },
  { id: 'disco-stage', name: 'MORI MICHI DISCO STAGE', type: 'stage' },
  { id: 'grass-stage', name: 'GRASS STAGE', type: 'stage' },
  { id: 'sand-stage', name: 'SAND STAGE', type: 'stage' },
  { id: 'hill-stage', name: 'HILL STAGE', type: 'stage' },
  { id: 'eikyo-stage', name: '影響亜細亜STAGE', type: 'stage' },
  { id: 'eatbeat', name: 'EATBEAT! STAGE', type: 'stage' },
  { id: 'eatbeat-ichi', name: 'EATBEAT!10（出店）', type: 'area' },
  { id: 'liverary', name: 'LIVERARY pre. エリア', type: 'area' },
  { id: 'tane', name: '種と旅と', type: 'area' },
  { id: 'yuenchi-market', name: 'SPLASH MARKET', type: 'area' },
  { id: 'yuenchi-market2', name: '遊園地MARKET', type: 'area' },
  { id: 'morimichi-disco', name: '森道食堂 DISCO支店', type: 'area' },
  { id: 'morimichi-umi', name: '森道食堂 海支店', type: 'area' },
  { id: 'kaigan6', name: '海岸通り六丁目', type: 'area' },
  { id: 'river-market', name: 'RIVER MARKET', type: 'area' },
  { id: 'kyoryu', name: 'KYORYU STREET', type: 'area' },
  { id: 'play-market', name: 'PLAY MARKET', type: 'area' },
  { id: 'little-okinawa', name: 'リトルオキナワ', type: 'area' },
  { id: 'fantastic', name: 'ファンタスティックマーケット', type: 'area' },
  { id: 'east-caravan', name: 'EAST CARAVAN', type: 'area' },
  { id: 'venture', name: 'VENTURE ONWARD by Purveyors', type: 'area' },
  { id: 'ukiuki', name: 'ウキウキ通り', type: 'area' },
  { id: 'kaigan1', name: '海岸通り一丁目', type: 'area' },
  { id: 'kaigan2', name: '海岸通り二丁目', type: 'area' },
  { id: 'kaigan3', name: '海岸通り三丁目', type: 'area' },
  { id: 'kaigan4', name: '海岸通り四丁目', type: 'area' },
  { id: 'kaigan5', name: '海岸通り五丁目', type: 'area' },
  { id: 'center-gai', name: '森道センター街', type: 'area' },
  { id: 'nagano', name: 'ながのなの', type: 'area' },
  { id: 'shibafu', name: '森道芝生広場・新京都会館', type: 'area' },
  { id: 'nonnon', name: 'のんのんパレード', type: 'area' },
  { id: 'shimanami', name: 'しまなみやまなみバイブス県', type: 'area' }
];

/* 出店ショップ（公式会場マップPDF「出店一覧」掲載・約420店）
   形式: [店名, カテゴリ, エリアID]
   カテゴリ: food / drink / sweets / goods / art */
const SHOP_DATA = [
  ["NORMAL","goods","liverary"],
  ["ZEZE","goods","liverary"],
  ["CHOWCHOW","goods","liverary"],
  ["City Dining Macy's","food","liverary"],
  ["カロリー軒","goods","liverary"],
  ["ひねもすのたりとsunday wine clab","drink","liverary"],
  ["TRESOL","goods","liverary"],
  ["A.N.D.","goods","liverary"],
  ["スパイスアワー","goods","liverary"],
  ["カレーショップ らんびー","food","liverary"],
  ["Bar kanata","goods","liverary"],
  ["スパイスカレーと無国籍料理 maai (間合い)","food","liverary"],
  ["JIRRI.","goods","liverary"],
  ["シヤチル","goods","liverary"],
  ["CoffeeSupreme","drink","liverary"],
  ["ブロッケン","goods","liverary"],
  ["炊々","goods","liverary"],
  ["幸福館","goods","liverary"],
  ["ネグラ(妄想インドカレーと越境庶民料理店)","food","liverary"],
  ["OFF","goods","liverary"],
  ["チーム銘々","goods","liverary"],
  ["OPERE","goods","liverary"],
  ["kuretal百貨センター","goods","liverary"],
  ["鋤田収集事務所","goods","liverary"],
  ["延命ランド","goods","liverary"],
  ["KIOSCO","goods","liverary"],
  ["JYUKU","goods","liverary"],
  ["NOTHING","goods","liverary"],
  ["Moloch","goods","liverary"],
  ["にしこはりこ","goods","liverary"],
  ["SUEKKO","goods","liverary"],
  ["LIONS©","goods","liverary"],
  ["namo. × merry yarn","goods","liverary"],
  ["チェルプ","goods","liverary"],
  ["スペースたのしい","goods","liverary"],
  ["Diorama & Panorama","goods","liverary"],
  ["RELAX ORIGINAL®","goods","liverary"],
  ["MAD BOXXX","goods","liverary"],
  ["Cane Cane","goods","liverary"],
  ["YUICHIRO TAMAKI","goods","liverary"],
  ["BOY","goods","liverary"],
  ["YAMASTORE","goods","liverary"],
  ["AWA by ukuuproject","goods","liverary"],
  ["JIAJIA","goods","liverary"],
  ["MATO OBJECTS STORE","goods","liverary"],
  ["KAN","goods","liverary"],
  ["CAN BUY RECORDS","art","liverary"],
  ["NU TRIAH","goods","liverary"],
  ["DELI","food","liverary"],
  ["rim","goods","liverary"],
  ["新町ビル（山の花/地想）","goods","liverary"],
  ["インターチェンジ by Good Broken Charm","goods","liverary"],
  ["MAKEDOO by Hiraparr","goods","liverary"],
  ["CHA CHA CHA BOOKS & CAFE","drink","liverary"],
  ["LIVERARY Extra","goods","liverary"],
  ["大橋裕之の似顔絵屋","art","liverary"],
  ["JAMとスロメ","goods","liverary"],
  ["MOLE FACTORY","goods","liverary"],
  ["sheep","goods","river-market"],
  ["山のふもと","goods","river-market"],
  ["島と山　nice things.&ACTIBASE","sweets","river-market"],
  ["kenta chujo","goods","river-market"],
  ["NAOKO HATA CERAMICS","goods","river-market"],
  ["sAn","goods","river-market"],
  ["chappo","goods","river-market"],
  ["MAZURKA","goods","river-market"],
  ["abundantism＋岡崎ぎゃざ","goods","river-market"],
  ["The Goggo(ザ ゴゴー)","goods","river-market"],
  ["quark+grenier","goods","river-market"],
  ["アポロコーヒーワークス","drink","river-market"],
  ["hankachi/beauty","goods","river-market"],
  ["大澤哲哉/HIKARI MASUDA","goods","river-market"],
  ["BAKERY dry river","food","river-market"],
  ["小菅くみ＋そで山かほ子","goods","river-market"],
  ["ペットの絵描きます　金森青葉","goods","river-market"],
  ["世界文庫 / 世界文庫アカデミー","art","river-market"],
  ["きびす堂","goods","river-market"],
  ["Instars","goods","river-market"],
  ["ituka","goods","river-market"],
  ["米粉sweets kinun.","sweets","river-market"],
  ["チーズケーキ tenton-テントン-","sweets","river-market"],
  ["tope.information","goods","river-market"],
  ["GRAPH.","goods","river-market"],
  ["CAFE SNUG","drink","river-market"],
  ["雑貨屋 孵","goods","river-market"],
  ["凸凹ことのは舎","goods","river-market"],
  ["四匹","goods","river-market"],
  ["September Poetry","goods","river-market"],
  ["鈴木 友紀","goods","river-market"],
  ["YOHEI NOGUCHI","goods","river-market"],
  ["松本 寛司","goods","river-market"],
  ["平野日奈子","goods","river-market"],
  ["ヤマネギターズ","goods","river-market"],
  ["茨木　伸恵","goods","river-market"],
  ["FARCRY BREWINGとNUMB&HAZY","drink","venture"],
  ["EYL","goods","venture"],
  ["AlexanderLeeChang","goods","venture"],
  ["Lue","goods","venture"],
  ["OLDMOUNTAIN","goods","venture"],
  ["haccoba Craft Sake Brewery","drink","venture"],
  ["移動帽子屋AURA","goods","venture"],
  ["atelier dehors","art","venture"],
  ["DUCKROW DEPART","goods","venture"],
  ["&NUT","goods","venture"],
  ["HAIDA","goods","venture"],
  ["honopottery","art","venture"],
  ["H.A.K.U MOUNTAIN SUPPLY","goods","venture"],
  ["YOKA×ONEPOTWONDER","goods","venture"],
  ["2-3-4SHOKUDO","goods","venture"],
  ["neru design works","goods","venture"],
  ["halo commodity","goods","venture"],
  ["DVERG","goods","venture"],
  ["Ashitabi","goods","venture"],
  ["caya","goods","venture"],
  ["mameritsuko","goods","venture"],
  ["fons","goods","venture"],
  ["中囿　義光","goods","venture"],
  ["ttoo","goods","venture"],
  ["MANIKA","goods","venture"],
  ["Sipilica","goods","venture"],
  ["rig footwear","goods","venture"],
  ["100mermaids and 100beasts","goods","venture"],
  ["stability","goods","venture"],
  ["神山隆二","goods","venture"],
  ["tempra garage & Marquez Shop","goods","venture"],
  ["HALFTRACK PRODUCTS","goods","venture"],
  ["NEVER WASTED/handson grip","goods","venture"],
  ["わたし、ローチョコレート","sweets","venture"],
  ["サンキューバナナ","goods","venture"],
  ["味噌湯 志なだ","goods","venture"],
  ["発酵惑星","goods","venture"],
  ["Paddy Field General Store","goods","kyoryu"],
  ["PEEPLE","goods","kyoryu"],
  ["yup","goods","kyoryu"],
  ["DECHO / NAPRON","goods","kyoryu"],
  ["光郷城 畑懐","goods","tane"],
  ["野母崎樺島製塩所","goods","tane"],
  ["minä perhonen","goods","tane"],
  ["igora","goods","tane"],
  ["Wine Bar Alpes","drink","tane"],
  ["久米桜三輪智成","goods","tane"],
  ["Burger Mania","food","ukiuki"],
  ["スープカレーよつば","food","ukiuki"],
  ["繁邦","goods","ukiuki"],
  ["VAAT","goods","ukiuki"],
  ["tak beans","goods","ukiuki"],
  ["餃子スラッピー","food","ukiuki"],
  ["MILK TEA SERVICE","drink","ukiuki"],
  ["ラーメンやんぐ","food","ukiuki"],
  ["かかん","goods","ukiuki"],
  ["NEWROSE","goods","ukiuki"],
  ["POMPONCAKES","sweets","ukiuki"],
  ["TSOL inc","goods","ukiuki"],
  ["KIKI NATURAL ICECREAM","sweets","ukiuki"],
  ["青果ミコト屋","goods","ukiuki"],
  ["Tiny N","goods","ukiuki"],
  ["fragrance yes","goods","ukiuki"],
  ["WUY","goods","ukiuki"],
  ["八方美米・八方美菜","goods","ukiuki"],
  ["TANUKI APPETIZING","goods","ukiuki"],
  ["Blanc a tokyo","goods","ukiuki"],
  ["山角や","goods","ukiuki"],
  ["KIKI WINE CLUB","drink","ukiuki"],
  ["石窯PIZZA屋台boccheno","food","kaigan1"],
  ["ぞうめし屋","goods","kaigan1"],
  ["Going Cafe","drink","kaigan1"],
  ["K's Pit","goods","kaigan1"],
  ["AOW","goods","kaigan1"],
  ["コジゴロ","goods","kaigan1"],
  ["KANNON＿PLUS","goods","kaigan1"],
  ["PAPERSKY STORE","goods","kaigan2"],
  ["サークルズ / サイクルクローク","goods","kaigan2"],
  ["CHAORAS（チャオラス）","goods","kaigan2"],
  ["one nova","goods","kaigan2"],
  ["サークルズ/PFM/CERCH","goods","kaigan2"],
  ["かかし","goods","kaigan2"],
  ["TUMBLEWEED","goods","kaigan2"],
  ["POT EQUIPMENT STORE","goods","kaigan2"],
  ["TACOMA FUJI RECORDS","food","kaigan2"],
  ["バーリカーズ","drink","kaigan2"],
  ["SELECT BY STAND","goods","kaigan2"],
  ["YELLOW vintage store","goods","kaigan2"],
  ["Eanbe","goods","kaigan2"],
  ["CARAVAN","goods","kaigan2"],
  ["お楽しみモール","goods","kaigan6"],
  ["全日本棍棒協会","goods","kaigan6"],
  ["寄道ハトバ","goods","kaigan6"],
  ["CYAARVO","goods","kaigan6"],
  ["epina×そうま農園","food","kaigan6"],
  ["那須の大きな食卓 by Chus","goods","kaigan6"],
  ["pile / ITONAMI","goods","kaigan6"],
  ["クライミングスペースＢＯＬＤ","goods","kaigan6"],
  ["スラックラインコミュニティシーモンキーズ","goods","kaigan6"],
  ["旅するパエリア","food","eatbeat-ichi"],
  ["THE BASKET","goods","eatbeat-ichi"],
  ["菓子ヒナゲシ","sweets","eatbeat-ichi"],
  ["雑踏","goods","eatbeat-ichi"],
  ["初耳の台湾","goods","eatbeat-ichi"],
  ["怪談商店 おばけ座","goods","eatbeat-ichi"],
  ["COFFEE HOUSE punkt.","drink","eatbeat-ichi"],
  ["TANJI","goods","eatbeat-ichi"],
  ["PlanetaryMuffin","goods","eatbeat-ichi"],
  ["AHSO a.k.a. ヅカデン","goods","eatbeat-ichi"],
  ["niente","goods","eatbeat-ichi"],
  ["LUZeSOMBRA","goods","eatbeat-ichi"],
  ["FISH BOWL COOK","goods","eatbeat-ichi"],
  ["The Source Diner","food","eatbeat-ichi"],
  ["RiCE おにぎり","sweets","eatbeat-ichi"],
  ["スヌーザー 静岡","goods","eatbeat-ichi"],
  ["EENYBREAKFAST＆SHOP","goods","eatbeat-ichi"],
  ["POCHAおじさん ＆ NOBY","goods","eatbeat-ichi"],
  ["VIVOBAREFOOT","goods","eatbeat-ichi"],
  ["MONK","goods","eatbeat-ichi"],
  ["anytee","goods","eatbeat-ichi"],
  ["仁井田本家","goods","eatbeat-ichi"],
  ["奈良醸造","goods","eatbeat-ichi"],
  ["そば爺よしみ","food","kaigan5"],
  ["サキアテジョーグー","goods","kaigan5"],
  ["DAN","goods","kaigan5"],
  ["yoknel","goods","kaigan5"],
  ["立呑み 海と花束","drink","kaigan5"],
  ["旅する占いパーム","goods","kaigan5"],
  ["旅する珈琲屋SweetMemoriesCoffee","drink","kaigan5"],
  ["CAFUNEとREEF KNOT COFFEE","drink","kaigan5"],
  ["OMIYAGE","goods","kaigan5"],
  ["おみごとスナック御美娘＆聖母呑俗夢　ドリームコラボ","goods","kaigan5"],
  ["TWO CHAPATI","goods","kaigan5"],
  ["chocobanashi","sweets","kaigan5"],
  ["発酵玄米三拍子feat.アワイ","goods","kaigan5"],
  ["SUNDAY SPICE","sweets","morimichi-disco"],
  ["喫茶hiraya","drink","morimichi-disco"],
  ["そのとうり","goods","morimichi-disco"],
  ["燦々-sansan-","goods","morimichi-disco"],
  ["narusoba","food","morimichi-disco"],
  ["だし・麺 未蕾","food","morimichi-disco"],
  ["SAVA!STORE","goods","kaigan3"],
  ["NAOT","goods","kaigan3"],
  ["スパイスカリー大陸","food","kaigan3"],
  ["遠藤マサヒロ","goods","kaigan3"],
  ["竹沢むつみ","goods","kaigan3"],
  ["jacou / suolo","goods","kaigan3"],
  ["BOOK TRUCK","art","kaigan3"],
  ["大衆食堂飯具","food","yuenchi-market"],
  ["鮨場まる","food","yuenchi-market"],
  ["ARC FARM","goods","yuenchi-market"],
  ["The Tiny Seed×BASIL CLUB","goods","yuenchi-market"],
  ["SAPERLIPOPETTE さっぺりぽぺっと","goods","yuenchi-market"],
  ["13倉庫yeti","goods","yuenchi-market"],
  ["森林食堂","food","yuenchi-market"],
  ["イチトサンブンノイチ","goods","yuenchi-market"],
  ["LAMP:TheSauna","goods","yuenchi-market"],
  ["Chè","goods","center-gai"],
  ["Origin Store","goods","center-gai"],
  ["HOME ECONOMICS EXPERIMENT","goods","center-gai"],
  ["SNEAKS by kakuozan larder & earlybirds breakfast","goods","center-gai"],
  ["TENTO","goods","center-gai"],
  ["ヤンガオ／影響亜細亜","goods","center-gai"],
  ["再来","goods","center-gai"],
  ["Pho321 Noodle bar／影響亜細亜","goods","center-gai"],
  ["HEY&Ho.／影響亜細亜","goods","center-gai"],
  ["MARA MAX Hi-Fi HQ／影響亜細亜","goods","center-gai"],
  ["クリンスイ","goods","center-gai"],
  ["影響亜細亜TravelingCOWBOOKS＋PageClimber","art","center-gai"],
  ["CultureMountainResearch","goods","center-gai"],
  ["ShopKAKUBARHYTHM,Test&Tiny","goods","center-gai"],
  ["MAGO FORNI","goods","kaigan4"],
  ["稲垣腸詰店","goods","kaigan4"],
  ["Quiet Village - California Parlor","goods","kaigan4"],
  ["cafeOPEN","drink","kaigan4"],
  ["Heritage Ranch Saloon","goods","kaigan4"],
  ["KCOFFEE","drink","yuenchi-market2"],
  ["Cat's ISSUEと森道大作戦！～うさぎを探せ～","goods","yuenchi-market2"],
  ["ENJOY SAUNA by SaunaCamp.","goods","yuenchi-market2"],
  ["IN/SECTS","goods","yuenchi-market2"],
  ["TIGER MOUNTAIN","goods","yuenchi-market2"],
  ["ホホホ座浄土寺店","goods","yuenchi-market2"],
  ["みじカルコレクション","goods","yuenchi-market2"],
  ["PORCO","goods","yuenchi-market2"],
  ["Ponchice","sweets","yuenchi-market2"],
  ["vint.","goods","yuenchi-market2"],
  ["musica print works","art","yuenchi-market2"],
  ["accessoriesmau×大岡弘晃　and more","goods","yuenchi-market2"],
  ["morocco","goods","yuenchi-market2"],
  ["Ain.Dah.ing","goods","yuenchi-market2"],
  ["まめちゃ／モリミチ喫茶室","drink","yuenchi-market2"],
  ["POSTO／モリミチ喫茶室","drink","yuenchi-market2"],
  ["円居","goods","yuenchi-market2"],
  ["mado cafe／モリミチ喫茶室","drink","yuenchi-market2"],
  ["喫茶toi／モリミチ喫茶室","drink","yuenchi-market2"],
  ["スコーン家HARU ／モリミチ喫茶室","drink","yuenchi-market2"],
  ["senkiya OMOCHI CLUB","goods","east-caravan"],
  ["TSUKIMO BAZAAR","goods","east-caravan"],
  ["てがみと文字Fluke(フルーク)","goods","east-caravan"],
  ["ノックの帽子屋","goods","east-caravan"],
  ["ripa","goods","east-caravan"],
  ["運麺PARK","food","east-caravan"],
  ["電気湯","goods","east-caravan"],
  ["どすこいドーナツ休日場所","sweets","east-caravan"],
  ["POP.POP.POP","goods","east-caravan"],
  ["旅するよしえのにがおえ屋さん","goods","east-caravan"],
  ["ぺぺぺ似顔絵店","art","east-caravan"],
  ["Jamboree","goods","east-caravan"],
  ["Canako Inoue","goods","east-caravan"],
  ["YURTAO","goods","east-caravan"],
  ["OTTOMO","goods","east-caravan"],
  ["ilu kamakura ゆげ","goods","east-caravan"],
  ["TPM BREWING","drink","east-caravan"],
  ["ヘブンズテーブル","goods","east-caravan"],
  ["笹塚ビールスタンド by MASUMOTOYA","drink","east-caravan"],
  ["KenichiKondo","goods","east-caravan"],
  ["チプカとプクチカ","goods","nagano"],
  ["takuramakan","goods","nagano"],
  ["NATURAL ANCHORS","goods","nagano"],
  ["重澤珈琲","drink","nagano"],
  ["TAIKO","goods","nagano"],
  ["umi neue","goods","nagano"],
  ["Fika","goods","nagano"],
  ["饅頭VERYMUCH","goods","nagano"],
  ["風景とみつめるタロット","goods","nagano"],
  ["OJAS PURE RAW CHOCOLATE","sweets","nagano"],
  ["Ph.D.","goods","nagano"],
  ["bowks","goods","nagano"],
  ["家具屋利右衛門","goods","nagano"],
  ["watson pottery studio","art","nagano"],
  ["runatsu kobayashi","goods","nagano"],
  ["石合昌史","goods","nagano"],
  ["POOLSIDE STORE","goods","nagano"],
  ["amijok/NorthSouthEastWest","goods","nagano"],
  ["Nobara Homestead Brewery","drink","nagano"],
  ["宮下果樹園","goods","nagano"],
  ["Chipakoya","goods","play-market"],
  ["人々","goods","play-market"],
  ["mature ha. Atelier shop","art","play-market"],
  ["ざ・デイリーズ","goods","play-market"],
  ["メルヘン大蔵のスゲ細工","goods","play-market"],
  ["QUE sera sera","goods","play-market"],
  ["25ris","goods","play-market"],
  ["古道具holo","goods","play-market"],
  ["にゃーにゃーごろごろパラダイス","goods","play-market"],
  ["ヌノモノワークス","goods","little-okinawa"],
  ["atelier sou","art","little-okinawa"],
  ["others","goods","little-okinawa"],
  ["石垣アパートメント","goods","little-okinawa"],
  ["Nantouyaki -南島焼-","goods","little-okinawa"],
  ["てすさび","goods","little-okinawa"],
  ["イチグスクモード","goods","little-okinawa"],
  ["島の装い。STORE","goods","little-okinawa"],
  ["commons","goods","little-okinawa"],
  ["羊羊 YOYO AN FACTORY","goods","little-okinawa"],
  ["GOZZA&MEGU","goods","little-okinawa"],
  ["HEY&HARETAKARA","goods","little-okinawa"],
  ["Aボールスタンド by 小桜・小梅","goods","little-okinawa"],
  ["東京台湾","goods","morimichi-umi"],
  ["Rice meals FoTan","sweets","morimichi-umi"],
  ["Little Nap COFFEE STAND","drink","morimichi-umi"],
  ["麺の樹ぼだい","food","morimichi-umi"],
  ["蜜香屋と豆んと森珈琲","drink","fantastic"],
  ["さやかのおむすびと堕楽暮","food","fantastic"],
  ["FOOD ORCHESTRA x SAN","food","fantastic"],
  ["七穀ベーカリー","food","fantastic"],
  ["お菓子あずき","sweets","fantastic"],
  ["WOOST engine meals / KITSUTSUKI","food","fantastic"],
  ["TIMOBAGELS","sweets","fantastic"],
  ["COCHI CAFE","drink","fantastic"],
  ["かわにし農園","food","fantastic"],
  ["さんかくの食卓","goods","fantastic"],
  ["野菜居酒屋いたぎ家","drink","fantastic"],
  ["graf kitchen","food","fantastic"],
  ["ダイヤメゾン","goods","fantastic"],
  ["ダルマワークス","goods","fantastic"],
  ["obrarte","goods","fantastic"],
  ["TE tea and eating","drink","fantastic"],
  ["RISE&WIN Brewing Co./KAMIKATZ BEER","drink","fantastic"],
  ["101010(トトト)","goods","fantastic"],
  ["hei","goods","fantastic"],
  ["HASHIMOTO NAOKO","goods","fantastic"],
  ["LIFE IS A JOURNEY! / ihatov","goods","fantastic"],
  ["カシューナッツ専門店　豆仁","goods","fantastic"],
  ["LACICO","goods","fantastic"],
  ["Tubu.","goods","fantastic"],
  ["yamyam STORE","goods","fantastic"],
  ["UNE TABLE","goods","fantastic"],
  ["RAINBOWFAM","goods","fantastic"],
  ["RumChai","drink","fantastic"],
  ["lovecycle","goods","fantastic"],
  ["澤邑直美","goods","fantastic"],
  ["saredo -されど-","goods","fantastic"],
  ["okapi","goods","fantastic"],
  ["泉州と堺の糸へん","goods","fantastic"],
  ["奥谷農園","food","fantastic"],
  ["maemuki suit!","goods","fantastic"],
  ["ぐびっと淡路島！","goods","fantastic"],
  ["puro(プーロ)","goods","fantastic"],
  ["源次郎商店","goods","shibafu"],
  ["KAMOGO","goods","shibafu"],
  ["宗像堂","goods","shibafu"],
  ["GOOD MORNING FARM","goods","shibafu"],
  ["Wrong Market","goods","shibafu"],
  ["タイ・モンゴル武者修行商会","goods","shibafu"],
  ["ラオス料理タマサート","food","shibafu"],
  ["Watte chai","drink","shibafu"],
  ["B+ND","goods","shibafu"],
  ["SUMI","goods","shibafu"],
  ["suba.kyoto","goods","shibafu"],
  ["ha ra","goods","shibafu"],
  ["３みっつ","goods","shibafu"],
  ["四月の魚","goods","shibafu"],
  ["magic room","goods","shibafu"],
  ["パルメラ","goods","shibafu"],
  ["モンゴルパン","food","shibafu"],
  ["HOZUBAG","goods","shibafu"],
  ["りんご","goods","shibafu"],
  ["小林酒店","drink","shibafu"],
  ["Sake World","drink","shibafu"],
  ["BAUM","goods","shibafu"],
  ["鴨庭","goods","shibafu"],
  ["TARELとcam","goods","shibafu"],
  ["山ねこ","goods","shibafu"],
  ["タコとケンタロー","goods","shibafu"],
  ["VOU/棒","goods","shibafu"],
  ["OFF THE RECORD","art","liverary"],
  ["社交酒場イム","drink","liverary"],
  ["BURGER STAND haveagoodtime. x daybyday","food","liverary"],
  ["BASE LAYER HOTEL","goods","liverary"],
  ["岩田商店","goods","eatbeat-ichi"],
  ["hitoha COFFEE & GRANOLA","drink","east-caravan"],
  ["IMAGINE.COFEEE","drink","shimanami"],
  ["エスニックスタンド メイクワンツー","food","shimanami"],
  ["がふ","goods","shimanami"],
  ["KAMERA","goods","shimanami"],
  ["Kougame","goods","shimanami"],
  ["コウボパン小さじいち","food","shimanami"],
  ["goffo","goods","shimanami"],
  ["山窩 -旅とてしごと-","goods","shimanami"],
  ["ジークマンストア","goods","shimanami"],
  ["自然食コタン","food","shimanami"],
  ["鈴木裕之の似顔絵屋さん","art","shimanami"],
  ["TYSON PIZZA","food","shimanami"],
  ["DADA NUTS BUTTER","food","shimanami"],
  ["Tanigaki","goods","shimanami"],
  ["WHW!","goods","shimanami"],
  ["テルツォテンポ","goods","shimanami"],
  ["ドットコミュ","goods","shimanami"],
  ["流しのビリヤニ","food","shimanami"],
  ["nuttsponchon","goods","shimanami"],
  ["NEWHELLOSHOP","goods","shimanami"],
  ["Passific Brewing","drink","shimanami"],
  ["フベン","goods","shimanami"],
  ["FLOAT","goods","shimanami"],
  ["BAILER","goods","shimanami"],
  ["ミルク工房そら","sweets","shimanami"],
  ["ヤンフー×イワサトミキ","goods","shimanami"],
  ["LA PITA DE MAISON CINQUANTECINQ","food","shimanami"],
  ["wineshop&stand slowcave","drink","shimanami"],
  ["TOKIIRO COFFEE ＆ POMO MAISON","drink","play-market"],
  ["hacu","goods","play-market"],
  ["FRECKLE","goods","play-market"],
  ["EN/ME","goods","ukiuki"],
  ["ORANGUTAN","goods","ukiuki"],
  ["KISO","goods","ukiuki"],
  ["Slō","goods","ukiuki"],
  ["TOO WOOD","goods","ukiuki"],
  ["PADDLERS COFFEE","drink","ukiuki"],
  ["山城果樹園","food","ukiuki"],
  ["LOU","goods","ukiuki"],
  ["AKITO COFFEE","drink","tane"],
  ["Appartement coffee","drink","tane"],
  ["ARBOL ICECREAM","sweets","tane"],
  ["ALO（アロ）","goods","tane"],
  ["伊藤渉","goods","tane"],
  ["Ethnic tam＋neutral","goods","tane"],
  ["HOWENE","goods","tane"],
  ["お酒と料理えいよう","food","tane"],
  ["カルパ","goods","tane"],
  ["樹和堂","goods","tane"],
  ["sagoggio","goods","tane"],
  ["sundaysfood","food","tane"],
  ["Sunday Bake Shop","sweets","tane"],
  ["SUNPEDAL（サンペダル）","goods","tane"],
  ["csew","goods","tane"],
  ["自然派料理店　糧","food","tane"],
  ["チェスト","goods","tane"],
  ["月とピエロ","goods","tane"],
  ["Tearoom Alpes","drink","tane"],
  ["nai","goods","tane"],
  ["パーラー江古田","food","tane"],
  ["Patisserie RaRe","sweets","tane"],
  ["パン屋 塩見","food","tane"],
  ["Bèe","goods","tane"],
  ["ひのめ","goods","tane"],
  ["Peg","goods","tane"],
  ["boat","goods","tane"],
  ["薪火野","food","tane"],
  ["MUBE","goods","tane"],
  ["湯宿 蒸気家 feat. Yusuke Kashima","goods","tane"],
  ["ラ・ブーランジェリー・ド・ハリマヤ","food","tane"],
  ["Ryohei Takamatsu","art","tane"],
  ["ワイン食堂トキワ","drink","tane"],
  ["wineshop flow","drink","tane"],
  ["hnn","food","tane"],
  ["ルヴァン甲田幹夫","food","tane"],
  ["Chè 333","sweets","center-gai"],
  ["MMF／影響亜細亜 Culture Shop","goods","center-gai"],
  ["OM sabaisabai／影響亜細亜 Culture Shop","goods","center-gai"],
  ["QUIET SPACE TOOL & FURNITURE／影響亜細亜 Culture Shop","goods","center-gai"],
  ["DIGAWEL／影響亜細亜 Culture Shop","goods","center-gai"],
  ["24PILLARS／影響亜細亜 Culture Shop","goods","center-gai"],
  ["TOKYO CULTUART by BEAMS／影響亜細亜","goods","center-gai"],
  ["Highway（南国灰道倶楽部）／影響亜細亜 Culture Shop","goods","center-gai"],
  ["BE A GOOD NEIGHBOR COFFEE KIOSK／影響亜細亜 Culture Shop","drink","center-gai"],
  ["農・豊・賛／nopposan","food","kaigan5"],
  ["森道結婚式＆海岸美容院","goods","kaigan5"],
  ["affordance + Onawa","goods","kaigan3"],
  ["SNOW SHOVELING [Caravan]","goods","kaigan3"],
  ["TORAYA EQUIPMENT","goods","kaigan2"],
  ["O2","goods","yuenchi-market"],
  ["oyatsupokke／モリミチ喫茶室","food","yuenchi-market2"],
  ["space／モリミチ喫茶室","drink","yuenchi-market2"],
  ["deli＆tea käwäsemi／モリミチ喫茶室","drink","yuenchi-market2"],
  ["ヒトトキ -人と木-／モリミチ喫茶室","drink","yuenchi-market2"],
  ["Felt coffee／モリミチ喫茶室","drink","yuenchi-market2"],
  ["uneclef／モリミチ喫茶室","drink","yuenchi-market2"],
  ["Nowhereman","goods","shibafu"],
  ["Méton","goods","shibafu"],
  ["ゆとなみ社","goods","shibafu"],
  ["和歌山酒場","drink","shibafu"],
  ["アトリエブルーボトル","goods","venture"],
  ["稲とアガベ","drink","venture"],
  ["ココ・ファーム・ワイナリー","drink","venture"],
  ["一二","goods","venture"],
  ["Purveyors","goods","venture"],
  ["Hi Hi Hi","goods","venture"],
  ["ぷくぷく醸造","drink","venture"],
  ["芙蓉酒造","drink","venture"],
  ["PLusBeat-月のうらがわ-","goods","venture"],
  ["BRING","goods","venture"],
  ["mörk","sweets","venture"],
  ["WONDER WORKS","goods","venture"]
];

/* ------- 自動生成（編集不要） -------
   icon は使用していないが、データ構造の後方互換のため空文字で保持。
   表記はラベル（label）のみで完結する。 */
const CAT = {
  food:  { label: 'フード',             icon: '' },
  drink: { label: 'ドリンク',            icon: '' },
  sweets:{ label: 'スイーツ',            icon: '' },
  goods: { label: '雑貨・ファッション',  icon: '' },
  art:   { label: 'アート・本・レコード', icon: '' }
};

/* すべての出店は「出店（shop）」カテゴリーに統合。
   サブカテゴリ（food/drink/goods/art等）はラベル表示用としてのみ残す。 */
const CAT_TARGET = {
  food: 'shop', drink: 'shop', sweets: 'shop',
  goods: 'shop', art: 'shop'
};

const ZONE_BY_ID = {};
ZONES.forEach(z => ZONE_BY_ID[z.id] = z);

const ARTISTS = ARTIST_NAMES.map((name, i) => ({
  id: 'a' + i, name, src: 'official'
}));

const SHOPS = SHOP_DATA.map((s, i) => {
  const [name, cat, zone] = s;
  const z = ZONE_BY_ID[zone];
  return {
    id: 's' + i, name, cat,
    catLabel: CAT[cat] ? CAT[cat].label : cat,
    catIcon: CAT[cat] ? CAT[cat].icon : '',
    targetType: CAT_TARGET[cat] || 'shop',  // 店舗 or ショップ
    zone, zoneName: z ? z.name : '',
    src: 'official'
  };
});

const AREAS = ZONES.map(z => ({
  id: z.id, name: z.name, type: z.type, src: 'official'
}));

/* app.js（ESMモジュール）から確実に参照できるよう window に公開する。
   classic script のトップレベル const は window プロパティにならないため。 */
window.MMA_DATA = {
  FESTIVAL: FESTIVAL,
  DATA_SOURCES: DATA_SOURCES,
  ARTISTS: ARTISTS,
  SHOPS: SHOPS,
  AREAS: AREAS,
  CAT: CAT,
  CAT_TARGET: CAT_TARGET
};
